MODULE PYOUT_SUB
!
! VERSION
!   18FEB25 AK Added helper routines for in-memory capture of RFM outputs.
!
! DESCRIPTION
!   Helper routines that populate and expose the data structures defined in
!   PYOUT_DAT.  The routines are used from the Python wrapper to retain
!   atmospheric profiles and spectral optical depth grids without writing to
!   intermediate files.
!
! VARIABLE KINDS
    USE KIND_DAT
!
! GLOBAL DATA
    USE PYOUT_DAT
!
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: PYOUT_RESET
  PUBLIC :: PYOUT_STORE_PROFILE
  PUBLIC :: PYOUT_COLLECT_SPECTRUM
  PUBLIC :: PYOUT_GET_SPECTRUM_SIZE
  PUBLIC :: PYOUT_FILL_SPECTRUM
!
CONTAINS
!
SUBROUTINE PYOUT_RESET ( NSPECTRA )
!
! ARGUMENTS
    INTEGER(I4), INTENT(IN) :: NSPECTRA
!
! LOCAL VARIABLES
    INTEGER(I4) :: I
!
  CALL PYOUT_CLEAR_PROFILE()
  CALL PYOUT_CLEAR_SPECTRA()
!
  CAPTURE_ENABLED = .TRUE.
  IF ( NSPECTRA .GT. 0 ) THEN
    ALLOCATE ( SPECTRA(NSPECTRA) )
    DO I = 1, NSPECTRA
      CALL PYOUT_RESET_ENTRY ( SPECTRA(I) )
    END DO
  END IF
!
END SUBROUTINE PYOUT_RESET
!
SUBROUTINE PYOUT_CLEAR_PROFILE()
!
  IF ( PROFILE%HAS_DATA ) THEN
    PROFILE%HAS_DATA = .FALSE.
    PROFILE%N_LEVELS = 0
  END IF
  IF ( ALLOCATED ( PROFILE%ALTITUDE ) ) DEALLOCATE ( PROFILE%ALTITUDE )
  IF ( ALLOCATED ( PROFILE%PRESSURE ) ) DEALLOCATE ( PROFILE%PRESSURE )
  IF ( ALLOCATED ( PROFILE%TEMPERATURE ) ) DEALLOCATE ( PROFILE%TEMPERATURE )
!
END SUBROUTINE PYOUT_CLEAR_PROFILE
!
SUBROUTINE PYOUT_CLEAR_SPECTRA()
!
! LOCAL VARIABLES
    INTEGER(I4) :: I
!
  IF ( ALLOCATED ( SPECTRA ) ) THEN
    DO I = 1, SIZE ( SPECTRA )
      CALL PYOUT_RESET_ENTRY ( SPECTRA(I) )
    END DO
    DEALLOCATE ( SPECTRA )
  END IF
!
END SUBROUTINE PYOUT_CLEAR_SPECTRA
!
SUBROUTINE PYOUT_RESET_ENTRY ( ENTRY )
!
! ARGUMENTS
    TYPE(SPECTRAL_RESULT), INTENT(INOUT) :: ENTRY
!
  ENTRY%HAS_DATA = .FALSE.
  ENTRY%N_LEVELS = 0
  ENTRY%N_POINTS = 0
  IF ( ALLOCATED ( ENTRY%ALTITUDE ) ) DEALLOCATE ( ENTRY%ALTITUDE )
  IF ( ALLOCATED ( ENTRY%PRESSURE ) ) DEALLOCATE ( ENTRY%PRESSURE )
  IF ( ALLOCATED ( ENTRY%TEMPERATURE ) ) DEALLOCATE ( ENTRY%TEMPERATURE )
  IF ( ALLOCATED ( ENTRY%WNO ) ) DEALLOCATE ( ENTRY%WNO )
  IF ( ALLOCATED ( ENTRY%CUMULATIVE ) ) DEALLOCATE ( ENTRY%CUMULATIVE )
!
END SUBROUTINE PYOUT_RESET_ENTRY
!
SUBROUTINE PYOUT_STORE_PROFILE()
!
! GLOBAL DATA
    USE ATMCOM_DAT, ONLY: NATM, HGTATM, PREATM, TEMATM
!
! LOCAL VARIABLES
    INTEGER(I4) :: NLEV
!
  IF ( .NOT. CAPTURE_ENABLED ) RETURN
  IF ( NATM .LE. 0 ) RETURN
  IF ( .NOT. ALLOCATED ( HGTATM ) ) RETURN
  IF ( .NOT. ALLOCATED ( PREATM ) ) RETURN
  IF ( .NOT. ALLOCATED ( TEMATM ) ) RETURN
!
  CALL PYOUT_CLEAR_PROFILE()
  NLEV = NATM
  PROFILE%HAS_DATA = .TRUE.
  PROFILE%N_LEVELS = NLEV
  ALLOCATE ( PROFILE%ALTITUDE(NLEV), PROFILE%PRESSURE(NLEV), &
             PROFILE%TEMPERATURE(NLEV) )
  PROFILE%ALTITUDE = REAL ( HGTATM, R8 )
  PROFILE%PRESSURE = REAL ( PREATM, R8 )
  PROFILE%TEMPERATURE = REAL ( TEMATM, R8 )
!
END SUBROUTINE PYOUT_STORE_PROFILE
!
SUBROUTINE PYOUT_COLLECT_SPECTRUM ( ISPC )
    USE FLGCOM_DAT, ONLY: LEVFLG, OPTFLG
    USE FULCOM_DAT, ONLY: NFUL, WNOFUL, OPTFUL
    USE LEVCOM_DAT, ONLY: NLEV, LEV, ITNLEV
    USE TANCOM_DAT, ONLY: NTAN, TAN
    USE ATMCOM_DAT, ONLY: HGTATM, PREATM, TEMATM
!
! ARGUMENTS
    INTEGER(I4), INTENT(IN) :: ISPC
!
! LOCAL VARIABLES
    INTEGER(I4) :: BASE_TAN
    INTEGER(I4) :: DOWN_COUNT
    INTEGER(I4) :: ILEV
    INTEGER(I4) :: SLOT
    INTEGER(I4) :: JCOL
    INTEGER(I4) :: IATM
!
  IF ( .NOT. CAPTURE_ENABLED ) RETURN
  IF ( .NOT. LEVFLG ) RETURN
  IF ( .NOT. OPTFLG ) RETURN
  IF ( NFUL .LE. 0 ) RETURN
  IF ( .NOT. ALLOCATED ( WNOFUL ) ) RETURN
  IF ( .NOT. ALLOCATED ( OPTFUL ) ) RETURN
  IF ( .NOT. ALLOCATED ( PREATM ) ) RETURN
  IF ( .NOT. ALLOCATED ( TEMATM ) ) RETURN
  IF ( .NOT. ALLOCATED ( SPECTRA ) ) RETURN
  IF ( ISPC .LT. 1 .OR. ISPC .GT. SIZE ( SPECTRA ) ) RETURN
!
  BASE_TAN = 0
  DO SLOT = 1, NTAN
    IF ( TAN(SLOT)%CLC ) THEN
      BASE_TAN = SLOT
      EXIT
    END IF
  END DO
  IF ( BASE_TAN .EQ. 0 ) RETURN
!
  DOWN_COUNT = 0
  DO ILEV = 1, NLEV
    IF ( LEV(ILEV)%IDR .NE. -1 ) CYCLE
    IF ( ITNLEV(BASE_TAN,ILEV) .GT. 0 ) DOWN_COUNT = DOWN_COUNT + 1
  END DO
  IF ( DOWN_COUNT .LE. 0 ) RETURN
!
  CALL PYOUT_RESET_ENTRY ( SPECTRA(ISPC) )
  SPECTRA(ISPC)%HAS_DATA = .TRUE.
  SPECTRA(ISPC)%N_LEVELS = DOWN_COUNT
  SPECTRA(ISPC)%N_POINTS = NFUL
  ALLOCATE ( SPECTRA(ISPC)%ALTITUDE(DOWN_COUNT) )
  ALLOCATE ( SPECTRA(ISPC)%PRESSURE(DOWN_COUNT) )
  ALLOCATE ( SPECTRA(ISPC)%TEMPERATURE(DOWN_COUNT) )
  ALLOCATE ( SPECTRA(ISPC)%CUMULATIVE(DOWN_COUNT, NFUL) )
  ALLOCATE ( SPECTRA(ISPC)%WNO(NFUL) )
!
  SLOT = 0
  DO ILEV = 1, NLEV
    IF ( LEV(ILEV)%IDR .NE. -1 ) CYCLE
    JCOL = ITNLEV(BASE_TAN,ILEV)
    IF ( JCOL .LE. 0 ) CYCLE
    SLOT = SLOT + 1
    IF ( SLOT .GT. DOWN_COUNT ) EXIT
    IATM = MAX ( MIN ( LEV(ILEV)%IAT, SIZE ( PREATM ) ), 1 )
    SPECTRA(ISPC)%ALTITUDE(SLOT) = REAL ( LEV(ILEV)%HGT, R8 )
    SPECTRA(ISPC)%PRESSURE(SLOT) = REAL ( PREATM(IATM), R8 )
    SPECTRA(ISPC)%TEMPERATURE(SLOT) = REAL ( TEMATM(IATM), R8 )
    SPECTRA(ISPC)%CUMULATIVE(SLOT,:) = OPTFUL(:,JCOL)
  END DO
  SPECTRA(ISPC)%WNO = WNOFUL
!
END SUBROUTINE PYOUT_COLLECT_SPECTRUM
!
SUBROUTINE PYOUT_GET_SPECTRUM_SIZE ( ISPC, STATUS, NLEVELS, NPOINTS )
!
! ARGUMENTS
    INTEGER(I4), INTENT(IN)  :: ISPC
    INTEGER(I4), INTENT(OUT) :: STATUS
    INTEGER(I4), INTENT(OUT) :: NLEVELS
    INTEGER(I4), INTENT(OUT) :: NPOINTS
!
  STATUS = 0
  NLEVELS = 0
  NPOINTS = 0
  IF ( .NOT. CAPTURE_ENABLED ) THEN
    STATUS = 1
    RETURN
  END IF
  IF ( .NOT. ALLOCATED ( SPECTRA ) ) THEN
    STATUS = 2
    RETURN
  END IF
  IF ( ISPC .LT. 1 .OR. ISPC .GT. SIZE ( SPECTRA ) ) THEN
    STATUS = 3
    RETURN
  END IF
  IF ( .NOT. SPECTRA(ISPC)%HAS_DATA ) THEN
    STATUS = 4
    RETURN
  END IF
  NLEVELS = SPECTRA(ISPC)%N_LEVELS
  NPOINTS = SPECTRA(ISPC)%N_POINTS
!
END SUBROUTINE PYOUT_GET_SPECTRUM_SIZE
!
SUBROUTINE PYOUT_FILL_SPECTRUM ( ISPC, STATUS, ALTITUDE, PRESSURE, &
                                 TEMPERATURE, WNO, CUMULATIVE )
!
! ARGUMENTS
    INTEGER(I4), INTENT(IN)  :: ISPC
    INTEGER(I4), INTENT(OUT) :: STATUS
    REAL(R8), INTENT(OUT) :: ALTITUDE(:)
    REAL(R8), INTENT(OUT) :: PRESSURE(:)
    REAL(R8), INTENT(OUT) :: TEMPERATURE(:)
    REAL(R8), INTENT(OUT) :: WNO(:)
    REAL(R8), INTENT(OUT) :: CUMULATIVE(:,:)
!
! LOCAL VARIABLES
    INTEGER(I4) :: NLEV
    INTEGER(I4) :: NPT
    INTEGER(I4) :: ILEV
!
  CALL PYOUT_GET_SPECTRUM_SIZE ( ISPC, STATUS, NLEV, NPT )
  IF ( STATUS .NE. 0 ) RETURN
!
  IF ( SIZE ( ALTITUDE ) .LT. NLEV .OR. &
       SIZE ( PRESSURE ) .LT. NLEV .OR. &
       SIZE ( TEMPERATURE ) .LT. NLEV ) THEN
    STATUS = 5
    RETURN
  END IF
  IF ( SIZE ( WNO ) .LT. NPT ) THEN
    STATUS = 6
    RETURN
  END IF
  IF ( SIZE ( CUMULATIVE, 1 ) .LT. NLEV .OR. SIZE ( CUMULATIVE, 2 ) .LT. NPT ) THEN
    STATUS = 7
    RETURN
  END IF
!
  DO ILEV = 1, NLEV
    ALTITUDE(ILEV) = SPECTRA(ISPC)%ALTITUDE(ILEV)
    PRESSURE(ILEV) = SPECTRA(ISPC)%PRESSURE(ILEV)
    TEMPERATURE(ILEV) = SPECTRA(ISPC)%TEMPERATURE(ILEV)
  END DO
  DO ILEV = 1, NPT
    WNO(ILEV) = SPECTRA(ISPC)%WNO(ILEV)
  END DO
  DO ILEV = 1, NLEV
    CUMULATIVE(ILEV,1:NPT) = SPECTRA(ISPC)%CUMULATIVE(ILEV,1:NPT)
  END DO
!
END SUBROUTINE PYOUT_FILL_SPECTRUM
!
END MODULE PYOUT_SUB
