PROGRAM DISORT_DRIVER
IMPLICIT NONE

!------------------------------------------------------------------------------!
!                               INPUT VARIABLES
!------------------------------------------------------------------------------!
INTEGER :: NLYR !NUMBER OF COMPUTATIONAL LAYERS
REAL, DIMENSION(:), ALLOCATABLE :: DTAUC 
INTEGER :: LC
! DTAU(LC) IS AN ARRAY OF OPTICAL DEPTHS OF THE COMPUTATIONAL LAYERS
! LC  :  for computational layers (each having a different
!           single-scatter albedo and/or phase function)
REAL, DIMENSION(:), ALLOCATABLE :: SSALB
!SINGLE SCATTER ALBEDOS OF COMPUTATIONAL LAYERS
!RATIO OF SCATTERING EFFICIENCY TO TOTAL EXTINCTION EFFICIENCY
!IF 1, THEN ALL EXTINCTION IS DUE TO SCATTERING
!IF 0, THEN ALL EXTINCTION IS DUE TO ABSORPTION
INTEGER :: NMOM 
!NUMBER OF PHASE FUNCTION MOMENTS (ALL TH SIGNIFICANT LEGENDRE COEFFICIENTS
!NOT INCLUDING THE ZEROTH MOMENT (WHICH IS ALWAYS 1 DUE TO THE NORMALIZATION
!CONDITION)
!IN A MULTI LAYER PROBLEM NMOM NUMBER O MOMENTS SHOULD BE SUPPLIED FOR EVERY
!LAYERM EVEN WHEN THE INDIVIDUAL LAYERS ARE CHARACTERIZED BY DIFFERENT PHASE
!FUNCTIONS.
!NMOM SHOULD BE > OR = TO NSTR
!NMOM IS NOT USED IN PROBLEMS WITHOUT SCATTERING
REAL, DIMENSION(:,:), ALLOCATABLE :: PMOM
!PMOM(K, LC): K = 0 TO NMOM, LC = 1 TO NLYR
!COEFFICIENTS IN LEGENDRE POLYNOMIAL EXPANSIONS OF PHASE FUNCTIONS FOR 
!COMPUTATIONAL LAYERS.
!P(MU) = SUM,K=0 TO NMOM( NMOM( 2K+1 ) PMOM(K) PK(MU) )
!WHERE P = PHASE FUNCTION, MU = COS(SCATTERING ANGLE),
!PK = KTH LEGENDRE POLYNOMIAL
!THE K=0 COEFFICIENT SHOULD BE 1 (AND WILL BE RESET AUTOMATICALLY).
!SUBROUTINE GETMOM MAY BE CALLED TO CALCULATE THE COEFFICIENTS IN SOME CASES.
REAL, DIMENSION(:), ALLOCATABLE :: TEMPER
!TEMPER(LEV), LEV = 0 TO NLYR, TEMPERATURES IN KELVIN OF LEVELS.
!TEMPERATURES ARE SPECIFIED IN LEVELS AND NOT LAYERS.
!PUT TOP LEVEL TEMPERATURE IN TEMPER(0).
!TOP AND BOTTOM LEVEL VALUES DO NOT NEED TO AGREE WITH TOP AND BOTTOM BOUNDARY
!TEMPERATURES (I.E. TEMPERATURE DISCONTINUITIES ALLOWED).
!ONLY NEEDED IN PLANK=TRUE
LOGICAL :: USRTAU
!F = RADIANT QUANTITIES TO BE RETURNED AT BOUNDARY OF EVERY COMPUTATIONAL LAYER
!T = RADIANT QUANTITIES TO BE RETURNED AT USER-SPECIFIED OPTICAL DEPTHS
!WHICH ARE SPECIFIED IN INCREASING ORDER BY NTAU AND UTATU(LU),
!WHERE LU = 1 TO NTAU
!UTAU(NTAU) MUST NOT EXCEED THE MAXIMUM OPTICAL DEPTH OF THE MEDIUM SET IN DTAUC
INTEGER :: NTAU
REAL, DIMENSION(:), ALLOCATABLE :: UTAU

INTEGER :: NSTR
!NUMBER OF COMPUTATIONAL POLAR ANGLES TO BE USED. SHOULD BE EVEN AND >=2
LOGICAL :: USRANG
!F = RAIDANT QUANTITIES TO BE RETURNED AT COMPUTATIONAL POLAR ANGLES, IN THIS
!CASE UMU WILL RETURN THE COSINES OF THE COPUTATIONAL POLAR ANGLES AND NUMU WILL
!RETURN THEIR NUMBER (=NSTR).
!T = RADIANT QUANTITIES TO BE RETURNED AT USED-SPECIFIED POLAR ANGLES, WHERE:
!NUMU = NO. OF POLAR ANGLES (0 IS LEGALT ONLY WHEN ONLYFL = TRUE)
!UMU(IU), WHERE IU = 1 TO NUMU, COSINES OF OUTPUT POLAR ANGLES IN INCREASING
!ORDER, MUST NOT HAVE ANY ZERO VALUES
INTEGER :: NUMU
REAL, DIMENSION(:), ALLOCATABLE :: UMU
INTEGER NPHI !NUMBER OF AZIMUTHAL ANGLES AT WHICH TO RETURN INTENSITIES
!0 IS LEGAL ONLY WHEN ONLYFL=TRUE
REAL, DIMENSION(:), ALLOCATABLE :: PHI
!PHI(J) = AZIMUTHAL OUTPUT ANGLES (IN DEGREES)
INTEGER :: IBCND !BOUNDARY CONDITIONS, PLEASE REFER TO DISORT.TXT
REAL :: FBEAM !INTENSITY OF INCIDENT PARALLEL BEAM AT TOP BOUNDARY.
!UNITS AS PLKAVG (DEFALUT W/M2) IF THERMAL SOURCES, OTHERWISE ARBITRARY UNITS
REAL :: UMU0 !COSINE OF POLAR ANGLE OF THE INCIDENT BEAM (POSITIVE)
!THE INCIDENT FLUX AT THE TOP OF THE ATMOSHPERE IS THEN UMU0*FBEAM
REAL :: PHI0 !AZIMUTHAL ANGLE OF THE INCIDENT BEAM (0 to 360 DEG)
REAL :: FISOT !INTENSITY OF TOP-BOUNDARY ISOTROPIC ILLUMINATION, UNITS AS FBEAM
!THE CORRESPONDING INCIDENT FLUX IS PI*FISOT
LOGICAL :: LAMBER !T - ISOTROPICALLY REFLECTING BOTTOM BOUNDARY, REQUIRES ALBEDO
!F - BIDIRECTIONALLY REFLECTING BOTTOM BOUNDARY, NEEDS FUNCTION FROM BDREF.F
REAL :: ALBEDO !BOTTOM BOUNDARY ALBEDO
REAL :: BTEMP !BOTTOM BOUNDARY TEMPERATURE, NEEDED ONLY IF PLANK=TRUE
REAL :: TTEMP !TOP BOUNDARY TEMPERATURE, NEEDED ONLY IF PLANK=TRUE
REAL :: TEMIS !EMISSIVITY OF TOP BOUNDARY, NEEDED ONLY IF PLANK=TRUE
LOGICAL :: PLANK !T -INCLUDE THERMAL EMISSION, F - IGNORE ALL THERMAL EMISSION
REAL :: WVNMLO, WVNMHI !WAVENUMBERS (CM-1) OF SPECTRAL INTERVAL OF INTEREST,
!USED ONLY BY PLANCK THERMAL EMISSION AND/OR BDREF
LOGICAL :: ONLYFL !T - RETURN FLUXES, FLUX DIVERGENCES AND MEAN INTENSITIES
!F - RETURN FLUXES, FLUX DIVERGENCES, MEAN INTENSITIES AND INTENSITIES
REAL :: ACCUR !CONVERGENCE CRITERION FOR AZIMUTHAL (FOURIER COSINE) SERIES
!REFER TO DISORT.TXT FOR MEANING
LOGICAL PRNT(5) !ARRAY OF LOGICAL PRINT FLAGS CAUSING SOME PRINTING
!VALUES 1 TO 5, REFER TO DISORT.TXT FOR LIST
CHARACTER  HEADER*127 !HEADER FOR PRINTS
LOGICAL :: DELTAMPLUS !T - USE NEW DELTA-M PLUS METHOD; F- DON'T USE, SEE DISORT
LOGICAL :: DO_PSEUDO_SPHERE !T - DOES PSEUDO SPHERICAL CORRECTION ON BEAM
!ATTENUATION TERM AND ON SOLAR ZENIT ANGLE, NOT EXPLAINED IN COMMENTS, BUT 
!DEFINED IN DISORT.F ON L2918)


!------------------------------------------------------------------------------!
!                         INTERNAL VARIABLES
!------------------------------------------------------------------------------!
REAL, PARAMETER :: EARTH_RADIUS = 6371.0 ![KM]
REAL, DIMENSION(:), ALLOCATABLE :: H_LYR !LAYER HEIGHT, USED IF DO_PSEUDO_SPHERE
REAL, DIMENSION(:,:,:), ALLOCATABLE :: RHOQ, RHOU !USED IN BRDEF
REAL, DIMENSION(:,:), ALLOCATABLE :: RHO_ACCURATE !ANALYTICAL BDREF RESULTS
REAL, DIMENSION(:), ALLOCATABLE :: EMUST, BEMST ! DIRECTIONAL EMISSIVITY AT
!USER AND QUADRATURE ANGLES, RESPECTIVELY
REAL, PARAMETER :: PI = 2.*ASIN(1.0)




!------------------------------------------------------------------------------!
!                               OUTPUT VARIABLES
!------------------------------------------------------------------------------!
REAL, DIMENSION(:), ALLOCATABLE :: RFLDIR !, RFLDIR(LU), DIRECT BEAM FLUX
!(WITHOUT DELTA-M SSCALING, SEE 
!https://doi.org/10.1175/1520-0469(1977)034<1408:TDMRYA>2.0.CO;2 )
REAL, DIMENSION(:), ALLOCATABLE :: RFLDN !RFLDN(LU), DIFFUSE DOWN FLUX (TOTAL
!MINUS DIRECT BEAM, WITHOUT DELTA-M SCALING)
REAL, DIMENSION(:), ALLOCATABLE :: FLUP !FLUP(LU), DIFFUSE UP-FLUX
REAL, DIMENSION(:), ALLOCATABLE :: DFDT !DFDT(LU), FLUX DIVERGENCE,
!CALCULATED AS D(NET FLUX)/D(OPTICAL DEPTH), WHERE NET FLUX INCLUDES DIRECT BEAM
REAL, DIMENSION(:), ALLOCATABLE :: UAVG !UAVG(LU), MEAN INTENSITY, INCL. DIRECT
!BEAM, NOT INCL DELTA-M SCALING
REAL, DIMENSION(:,:,:), ALLOCATABLE :: UU !UU(IU,LU,J) INTENSITY (IF ONLYFL =
!FALSE, ZEROS OTHERWISE)
REAL, DIMENSION(:), ALLOCATABLE :: ALBMED !ALBMED(IU), ALBEDO OF THE MEDIUM AS
!A FUNCTION OF INCIDENT BEAM ANGLE COSINE UMU(IU), ONLY IF IBCND=1
REAL, DIMENSION(:), ALLOCATABLE :: TRNMED !TRNMED(IU) TRANSMISSIVITY OF 
!THE MEDIUM AS A FUNCTION OF INXIDENT BEAM ANGLE COSINE UMU(IU), ONLY IF IBCND=1

!------------------------------------------------------------------------------!
!                               VARIABLE ASSIGNMENT
!------------------------------------------------------------------------------!
USRTAU = .TRUE.
USRANG = .TRUE.
PLANK = .FALSE.
LAMBER = .TRUE.
ONLYFL = .FALSE.
DELTAMPLUS = .FALSE.
DO_PSEUDO_SPHERE = .FALSE.


NLYR = 1
NSTR = 16
NMOM = NSTR
NUMU = 6; IF(.NOT.USRANG) NUMU = NSTR
NPHI = 1
IBCND = 0
NTAU = 2; IF(.NOT.USRTAU) NTAU = NLYR + 1

!THIS BIT BELOW ALLOCATES ARRAYS
ALLOCATE( DTAUC( NLYR ), SSALB( NLYR ), PMOM( 0:NMOM, NLYR ), TEMPER( 0:NLYR ),&
         H_LYR( 0:NLYR ), UTAU( NTAU ), UMU( NUMU ), PHI( NPHI ) )
ALLOCATE( RHOQ(NSTR/2, 0:NSTR/2, 0:(NSTR-1)), RHOU(NUMU, 0:NSTR/2, 0:(NSTR-1)),&
          EMUST( NUMU ), BEMST( NSTR/2 ), RHO_ACCURATE( NUMU, NPHI ) )
ALLOCATE( RFLDIR (NTAU ), RFLDN( NTAU ), FLUP( NTAU ), DFDT( NTAU ), &
          UAVG( NTAU ), ALBMED( NUMU ), TRNMED( NUMU ), UU( NUMU, NTAU, NPHI ) )

!THIS BIT BELOW ZEROS THE ALLOCATED ARRAYS 
DTAUC = 0.0; SSALB = 0.0; PMOM = 0.0; TEMPER = 0.0; UTAU = 0.0; UMU = 0.0;
PHI = 0.0; H_LYR = 0.0; RHOQ = 0.0; RHOU = 0.0; EMUST = 0.0; BEMST = 0.0;
RHO_ACCURATE = 0.0; RFLDIR = 0.0; RFLDN = 0.0; FLUP = 0.0; DFDT = 0.0;
UAVG = 0.0; UU = 0.0; ALBMED = 0.0; TRNMED = 0.0;


!CONTINUES VARIABLE ASSIGNMENT
DTAUC( 1 ) = 0.03125
SSALB( 1 ) = 0.2

UTAU( 1 ) = 0.0; UTAU( 2 )  = 0.03125

UMU( 1 )  = -1.0; UMU( 2 )  = -0.5; UMU( 3 )  = -0.1
UMU( 4 )  =  0.1; UMU( 5 )  =  0.5; UMU( 6 )  =  1.0

UMU0 = 0.1
PHI0 = 0.0

PHI ( 1 ) = 0.0

ALBEDO = 0.0

CALL GETMOM(2, 0.0, NSTR, PMOM)

FBEAM = PI / UMU0
FISOT = 0.0

WRITE( HEADER,* ) 'this is a dummy run with probably unphysical conditions.'


!PRNT
!TEMPER
!WVNMLO
!WVNMHI

!FBEAM            
!FISOT
!ALBEDO
!BTEMP
!TTEMP
!TEMIS
!H_LYR
!RHOQ
!RHOU
!RHO_ACCURATE
!BEMST
!EMUST
!ACCUR
!HEADER
!RFLDIR
!RFLDN
!FLUP
!DFDT
!UAVG
!UU
!ALBMED
!TRNMED


!------------------------------------------------------------------------------!
!                               MAIN PROGRAM
!------------------------------------------------------------------------------!
CALL DISORT( NLYR, NMOM, NSTR, NUMU, NPHI, NTAU,           &
             USRANG, USRTAU, IBCND, ONLYFL, PRNT,          &
             PLANK, LAMBER, DELTAMPLUS, DO_PSEUDO_SPHERE,  &          
             DTAUC, SSALB, PMOM, TEMPER, WVNMLO, WVNMHI,   & 
             UTAU, UMU0, PHI0, UMU, PHI, FBEAM,            &                        
             FISOT, ALBEDO, BTEMP, TTEMP, TEMIS,           &
             EARTH_RADIUS, H_LYR,                          &
             RHOQ, RHOU, RHO_ACCURATE, BEMST, EMUST,       &
             ACCUR,  HEADER,                               &
             RFLDIR, RFLDN, FLUP, DFDT, UAVG, UU,          &
             ALBMED, TRNMED )


CALL PRTFIN2(NTAU, NUMU, NUMU, NTAU, UTAU, UMU, UU, NPHI, PHI)

DEALLOCATE( DTAUC, SSALB, PMOM, TEMPER, UTAU, UMU, PHI, H_LYR )
DEALLOCATE( RHOQ, RHOU, EMUST, BEMST, RHO_ACCURATE )
DEALLOCATE( RFLDIR, RFLDN, FLUP, DFDT, UAVG, ALBMED, TRNMED, UU )

END PROGRAM DISORT_DRIVER

